spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recruit?useUnicode=true&characterEncoding=utf8
    username: root
    password:
registerRestrict:
    timeInMinutes: 1
    count: 10
email:
  from:
    account: 13751310017@163.com    
    password: za88326052
  smtpHost: smtp.163.com
  protocol: smtp
